#ifndef _CHARACTERAUDIO_H_
#define _CHARACTERAUDIO_H_

#include "types.h"
#include "NL/nlMath.h"

#include "Game/GameAudio.h"
#include "Game/Physics/PhysicsCharacter.h"
#include "Game/Sys/audio.h"

class cCharacter;
class cTeam;
class GameInfoManager;

enum CharDialogueType
{
    CHAR_DIALOGUE_ATTACK = 0,
    CHAR_DIALOGUE_GET_HIT = 1,
    CHAR_DIALOGUE_HIT = 2,
    CHAR_DIALOGUE_PAIN = 3,
    CHAR_DIALOGUE_ELECTROCUTE = 4,
    CHAR_DIALOGUE_WAVE = 5,
    CHAR_DIALOGUE_EXERT = 6,
    CHAR_DIALOGUE_KICK = 7,
    CHAR_CLAP = 8,
    CHAR_FOOTSTEP_WALK = 9,
    CHAR_FOOTSTEP_RUN = 10,
};

struct CharDialogueSFXInfo
{
    /* 0x0 */ int charDialogueSFXIndex;
    /* 0x4 */ int numRandomSFX;
}; // total size: 0x8

namespace Audio
{

enum eCharSFX
{
    CHARSFX_NONE = 0,
    CHARSFX_RUN_01 = 1,
    CHARSFX_RUN_02 = 2,
    CHARSFX_RUN_03 = 3,
    CHARSFX_RUN_04 = 4,
    CHARSFX_RUN_05 = 5,
    CHARSFX_WALK_01 = 6,
    CHARSFX_WALK_02 = 7,
    CHARSFX_WALK_03 = 8,
    CHARSFX_WALK_04 = 9,
    CHARSFX_WALK_05 = 10,
    CHARSFX_LAND = 11,
    CHARSFX_SLIDE = 12,
    CHARSFX_JUMP = 13,
    CHARSFX_TURN = 14,
    CHARSFX_DEKE_LEFT = 15,
    CHARSFX_DEKE_RIGHT = 16,
    CHARSFX_BODYFALL = 17,
    CHARSFX_KICK_ATTEMPT = 18,
    CHARSFX_KICK_SUPER = 19,
    CHARSFX_SHOT_WINDUP = 20,
    CHARSFX_SHOT_LOCK = 21,
    CHARSFX_SHOT_RELEASE = 22,
    CHARSFX_S2S_METER_GLOW = 23,
    CHARSFX_HIT_BODY = 24,
    CHARSFX_HIT_BODY_BONE = 25,
    CHARSFX_HIT_SLIDE = 26,
    CHARSFX_BODYFALL_BONECRUNCH = 27,
    CHARSFX_SUPER_KICK_WINDUP = 28,
    CHARSFX_PWRUP_MUSH_IN_EFFECT = 29,
    CHARSFX_PWRUP_STAR_IN_EFFECT = 30,
    CHARSFX_SHELL_FREEZE_HIT = 31,
    CHARSFX_SHELL_FREEZE_END = 32,
    CHARSFX_EFFORTS_ATTACK_01 = 33,
    CHARSFX_EFFORTS_ATTACK_02 = 34,
    CHARSFX_EFFORTS_ATTACK_03 = 35,
    CHARSFX_EFFORTS_HIT_01 = 36,
    CHARSFX_EFFORTS_HIT_02 = 37,
    CHARSFX_EFFORTS_HIT_03 = 38,
    CHARSFX_EFFORTS_GET_HIT_01 = 39,
    CHARSFX_EFFORTS_GET_HIT_02 = 40,
    CHARSFX_EFFORTS_GET_HIT_03 = 41,
    CHARSFX_EFFORTS_PAIN_01 = 42,
    CHARSFX_EFFORTS_PAIN_02 = 43,
    CHARSFX_EFFORTS_PAIN_03 = 44,
    CHARSFX_EFFORTS_PAIN_04 = 45,
    CHARSFX_EFFORTS_PAIN_05 = 46,
    CHARSFX_EFFORTS_ELECTROCUTE_01 = 47,
    CHARSFX_EFFORTS_ELECTROCUTE_02 = 48,
    CHARSFX_EFFORTS_ELECTROCUTE_03 = 49,
    CHARSFX_EFFORTS_EXERT_01 = 50,
    CHARSFX_EFFORTS_EXERT_02 = 51,
    CHARSFX_EFFORTS_EXERT_03 = 52,
    CHARSFX_EFFORTS_KICK_01 = 53,
    CHARSFX_EFFORTS_KICK_02 = 54,
    CHARSFX_EFFORTS_KICK_03 = 55,
    CHARSFX_EFFORTS_DAZED = 56,
    CHARSFX_EFFORTS_HEAD_SHAKE = 57,
    CHARSFX_EFFORTS_KICK_SUPER = 58,
    CHARSFX_EFFORTS_SHOT_WINDUP = 59,
    CHARSFX_EFFORTS_STS_JUMP_01 = 60,
    CHARSFX_EFFORTS_STS_FLOAT_01 = 61,
    CHARSFX_EFFORTS_STS_KICK_01 = 62,
    CHARSFX_EFFORTS_PERFECT_PASS = 63,
    CHARSFX_BREATH_WITH_BALL = 64,
    CHARSFX_CALL_HEY_01 = 65,
    CHARSFX_CALL_HEY_02 = 66,
    CHARSFX_CALL_WO_01 = 67,
    CHARSFX_CALL_WO_02 = 68,
    CHARSFX_CALL_PERFECT_PASS = 69,
    CHARSFX_DAZED = 70,
    CHARSFX_HEAD_POP = 71,
    CHARSFX_ELECTROCUTED = 72,
    CHARSFX_THROW = 73,
    CHARSFX_SWISH_UP_01 = 74,
    CHARSFX_SWISH_UP_02 = 75,
    CHARSFX_SWISH_UP_03 = 76,
    CHARSFX_SWISH_DOWN_01 = 77,
    CHARSFX_SWISH_DOWN_02 = 78,
    CHARSFX_SWISH_DOWN_03 = 79,
    CHARSFX_GEN_STOS_JUMP = 80,
    CHARSFX_GEN_STOS_FLOAT = 81,
    CHARSFX_GEN_STOS_FLOAT_HYPER = 82,
    CHARSFX_NIS_CLAP_01 = 83,
    CHARSFX_NIS_CLAP_02 = 84,
    CHARSFX_NIS_CLAP_03 = 85,
    CHARSFX_NIS_SPIN_LOOP = 86,
    CHARSFX_BOWSER_ENTER = 87,
    CHARSFX_BOWSER_ACTIVATE = 88,
    CHARSFX_BOWSER_HOWL_01 = 89,
    CHARSFX_BOWSER_HOWL_02 = 90,
    CHARSFX_BOWSER_HOWL_03 = 91,
    CHARSFX_BOWSER_CHARGE_01 = 92,
    CHARSFX_BOWSER_CHARGE_02 = 93,
    CHARSFX_BOWSER_BREATH_FIRE = 94,
    CHARSFX_CRITTER_HIT_NET = 95,
    CHARSFX_CRITTER_EFFORTS_CATCH_MOUTH = 96,
    CHARSFX_CRITTER_EFFORTS_FEAR = 97,
    CHARSFX_CRITTER_EFFORTS_PUZZLED = 98,
    CHARSFX_CRITTER_EFFORTS_ANGER = 99,
    CHARSFX_SUPER_LEFT_LEG_SERVO = 100,
    CHARSFX_SUPER_RIGHT_LEG_SERVO = 101,
    CHARSFX_TOAD_NIS_GOAL_HIGH_01 = 102,
    CHARSFX_TOAD_NIS_GOAL_LOW_01 = 103,
    CHARSFX_HAM_NIS_GOAL_HIGH_01 = 104,
    CHARSFX_HAM_NIS_GOAL_LOW_01 = 105,
    CHARSFX_KOOPA_NIS_GOAL_HIGH_01 = 106,
    CHARSFX_KOOPA_NIS_GOAL_LOW_01 = 107,
    CHARSFX_BIRDO_NIS_GOAL_HIGH_01 = 108,
    CHARSFX_BIRDO_NIS_GOAL_LOW_01 = 109,
    CHARSFX_DAISY_NIS_ENTER_HOME_01 = 110,
    CHARSFX_DAISY_NIS_ENTER_AWAY_01 = 111,
    CHARSFX_DAISY_NIS_ATTITUDE_01 = 112,
    CHARSFX_DAISY_NIS_GOAL_HIGH_01 = 113,
    CHARSFX_DAISY_NIS_GOAL_LOW_01 = 114,
    CHARSFX_DAISY_NIS_GAME_WIN_01 = 115,
    CHARSFX_DK_WIN_HOME_LOW = 116,
    CHARSFX_DK_END_GAME_HOME = 117,
    CHARSFX_DK_ATTITUDE_HOME_CHEST = 118,
    CHARSFX_DK_NIS_ENTER_HOME_01 = 119,
    CHARSFX_DK_NIS_ENTER_AWAY_01 = 120,
    CHARSFX_DK_NIS_ATTITUDE_01 = 121,
    CHARSFX_DK_NIS_GOAL_HIGH_00 = 122,
    CHARSFX_DK_NIS_GOAL_HIGH_01 = 123,
    CHARSFX_DK_NIS_GOAL_LOW_01 = 124,
    CHARSFX_DK_NIS_GAME_WIN_01 = 125,
    CHARSFX_LUIGI_NIS_ENTER_HOME_01 = 126,
    CHARSFX_LUIGI_NIS_ENTER_AWAY_01 = 127,
    CHARSFX_LUIGI_NIS_ATTITUDE_01 = 128,
    CHARSFX_LUIGI_NIS_GOAL_HIGH_01 = 129,
    CHARSFX_LUIGI_NIS_GOAL_LOW_01 = 130,
    CHARSFX_LUIGI_NIS_GAME_WIN_01 = 131,
    CHARSFX_MARIO_NIS_ENTER_HOME_01 = 132,
    CHARSFX_MARIO_NIS_ENTER_AWAY_01 = 133,
    CHARSFX_MARIO_NIS_ATTITUDE_01 = 134,
    CHARSFX_MARIO_NIS_ATTITUDE_02 = 135,
    CHARSFX_MARIO_NIS_GOAL_HIGH_01 = 136,
    CHARSFX_MARIO_NIS_GOAL_HIGH_02 = 137,
    CHARSFX_MARIO_NIS_GOAL_LOW_01 = 138,
    CHARSFX_MARIO_NIS_GAME_WIN_01 = 139,
    CHARSFX_MARIO_NIS_GAME_WIN_02 = 140,
    CHARSFX_PEACH_NIS_ENTER_HOME_01 = 141,
    CHARSFX_PEACH_NIS_ENTER_AWAY_01 = 142,
    CHARSFX_PEACH_NIS_ATTITUDE_01 = 143,
    CHARSFX_PEACH_NIS_GOAL_HIGH_01 = 144,
    CHARSFX_PEACH_NIS_GOAL_LOW_01 = 145,
    CHARSFX_PEACH_NIS_GAME_WIN_01 = 146,
    CHARSFX_WALUIGI_NIS_ENTER_HOME_01 = 147,
    CHARSFX_WALUIGI_NIS_ENTER_AWAY_01 = 148,
    CHARSFX_WALUIGI_NIS_ATTITUDE_01 = 149,
    CHARSFX_WALUIGI_NIS_GOAL_HIGH_01 = 150,
    CHARSFX_WALUIGI_NIS_GOAL_LOW_01 = 151,
    CHARSFX_WALUIGI_NIS_GAME_WIN_01 = 152,
    CHARSFX_WARIO_NIS_ENTER_HOME_01 = 153,
    CHARSFX_WARIO_NIS_ENTER_AWAY_01 = 154,
    CHARSFX_WARIO_NIS_ATTITUDE_01 = 155,
    CHARSFX_WARIO_NIS_GOAL_HIGH_01 = 156,
    CHARSFX_WARIO_NIS_GOAL_LOW_01 = 157,
    CHARSFX_WARIO_NIS_GAME_WIN_01 = 158,
    CHARSFX_YOSHI_NIS_ENTER_HOME_01 = 159,
    CHARSFX_YOSHI_NIS_ENTER_AWAY_01 = 160,
    CHARSFX_YOSHI_NIS_ATTITUDE_01 = 161,
    CHARSFX_YOSHI_NIS_GOAL_HIGH_01 = 162,
    CHARSFX_YOSHI_NIS_GOAL_LOW_01 = 163,
    CHARSFX_YOSHI_NIS_GAME_WIN_01 = 164,
    CHARSFX_SUPER_NIS_ENTER_HOME_01 = 165,
    CHARSFX_SUPER_NIS_ENTER_AWAY_01 = 166,
    CHARSFX_SUPER_NIS_ATTITUDE_01 = 167,
    CHARSFX_SUPER_NIS_GOAL_HIGH_01 = 168,
    CHARSFX_SUPER_NIS_GOAL_LOW_01 = 169,
    CHARSFX_SUPER_NIS_GAME_WIN_01 = 170,
    CHARSFX_MYST_NIS_ENERGY_BLAST_01 = 171,
    CHARSFX_MYST_NIS_ROCKET_BOOTS_01 = 172,
    NUM_CHARSFX = 173,
};

class cCharacterSFX : public cGameSFX
{
public:
    cCharacterSFX();
    virtual ~cCharacterSFX();
    virtual void Init();
    virtual uintptr_t Play(Audio::SoundAttributes& attrs);

    unsigned long Play(Audio::eCharSFX sfxType, float fVolume, float fPan, float fAttenuate);
    unsigned long Play3D(Audio::eCharSFX sfxType, PosUpdateMethod posUpdateMethod, float fMaxVolume, float fAttenuate);
    void Stop(Audio::eCharSFX sfxType, cGameSFX::StopFlag flag);
    unsigned long PlayRandomCharDialogue(CharDialogueType dType, PosUpdateMethod posUpdateMethod, float fVol, float fDelay, bool bAvoidCurrent);
    uintptr_t PlayRandomCharDialogue(CharDialogueType dType, Audio::SoundAttributes& sndAttributes, bool bAvoidCurrent, unsigned long* pOutSfx);
    bool IsPlayingRandomCharDialogue(CharDialogueType dType);
    void StopPlayingRandomCharDialogue(CharDialogueType dType);
    void StopPlayingAllRandomCharDialogue();
    void StopPlayingAllCharDialogue();
    int PlayRandomWalkFootstep(float fVol, bool bNoRepeat);
    static uintptr_t PlayNISRandomCharDialogue(CharDialogueType dialogueType, NisCharacterClass charIdentifier, float fVol, float fDelay, bool bIs3D, const nlVector3* pInitialPosVector, const nlVector3* pInitialDirVector, unsigned long* unkPtr);
    static cCharacter* GetCharacterFromNisCharClass(NisCharacterClass charIdentifier);
    void StartMovementLoop();
    void StopMovementLoop();
    bool IsMovementLoopPlaying();
    bool IsMovementLoopStarted();

    /* 0x034 */ int mSoundTypeEnumMap[173];
    /* 0x2E8 */ float mDebugTimer[173];
    /* 0x59C */ SoundStrToIDNode mCharSFX[173]; // size differs from dwarf data
    /* 0x3390 */ s32 mGroup;
    /* 0x3394 */ PhysicsObject* mpPhysObj;
    /* 0x3398 */ SFXEmitter* mpMovementLoopSound;
    /* 0x339C */ f32 m_unk_0x339C;
    /* 0x33A0 */ bool m_unk_0x33A0;
}; // total size: 0x30E8

} // namespace Audio

#endif // _CHARACTERAUDIO_H_
