#ifndef _NLFUNCTION1_H_
#define _NLFUNCTION1_H_

#include "NL/nlFunctionCommon.h"

#ifndef _NLFUNCTION_PRIMARY_DEFINED_
#define _NLFUNCTION_PRIMARY_DEFINED_

#define NLF_GENERATE_PRIMARY_WRAPPER
#include "NL/detail/nlFunction1PreProcTemplate.h"
#undef NLF_GENERATE_PRIMARY_WRAPPER

#endif // _NLFUNCTION_PRIMARY_DEFINED_

#ifndef _NLFUNCTION_ARITY1_DEFINED_
#define _NLFUNCTION_ARITY1_DEFINED_

#define NLF_CLASS Function1
#define NLF_TEMPLATE_PARAMETERS typename ReturnType, typename P1
#define NLF_TEMPLATE_ARGUMENTS ReturnType, P1
#define NLF_PARAMETER_TYPES P1
#define NLF_PARAMETER_DECLARATIONS P1 p0
#define NLF_ARGUMENT_NAMES p0
#define NLF_COMMA_PARAMETER_DECLARATIONS , P1 p0
#define NLF_COMMA_ARGUMENT_NAMES , p0
#define NLF_ARITY 1
#include "NL/detail/nlFunction1PreProcTemplate.h"
#undef NLF_ARITY
#undef NLF_COMMA_ARGUMENT_NAMES
#undef NLF_COMMA_PARAMETER_DECLARATIONS
#undef NLF_ARGUMENT_NAMES
#undef NLF_PARAMETER_DECLARATIONS
#undef NLF_PARAMETER_TYPES
#undef NLF_TEMPLATE_ARGUMENTS
#undef NLF_TEMPLATE_PARAMETERS
#undef NLF_CLASS

#endif // _NLFUNCTION_ARITY1_DEFINED_

#endif // _NLFUNCTION1_H_
