#ifndef _AIPLAY_H_
#define _AIPLAY_H_

#include "Game/AI/Fielder.h"
#include "Game/AI/DecisionEntity.h"

enum eAIPlay
{
    AIPLAY_NULL = 0,
    AIPLAY_OFFENSE_STRIKER_AGGRESSIVE = 1,
    AIPLAY_OFFENSE_STRIKER_MODERATE = 2,
    AIPLAY_OFFENSE_STRIKER_PASSIVE = 3,
    AIPLAY_OFFENSE_WINGER_AGGRESSIVE = 4,
    AIPLAY_OFFENSE_WINGER_MODERATE = 5,
    AIPLAY_OFFENSE_WINGER_PASSIVE = 6,
    AIPLAY_OFFENSE_MIDFIELD_AGGRESSIVE = 7,
    AIPLAY_OFFENSE_MIDFIELD_MODERATE = 8,
    AIPLAY_OFFENSE_MIDFIELD_PASSIVE = 9,
    AIPLAY_OFFENSE_DEFENDER_AGGRESSIVE = 10,
    AIPLAY_OFFENSE_DEFENDER_MODERATE = 11,
    AIPLAY_OFFENSE_DEFENDER_PASSIVE = 12,
    AIPLAY_DEFENSE_STRIKER_AGGRESSIVE = 13,
    AIPLAY_DEFENSE_STRIKER_MODERATE = 14,
    AIPLAY_DEFENSE_STRIKER_PASSIVE = 15,
    AIPLAY_DEFENSE_WINGER_AGGRESSIVE = 16,
    AIPLAY_DEFENSE_WINGER_MODERATE = 17,
    AIPLAY_DEFENSE_WINGER_PASSIVE = 18,
    AIPLAY_DEFENSE_MIDFIELD_AGGRESSIVE = 19,
    AIPLAY_DEFENSE_MIDFIELD_MODERATE = 20,
    AIPLAY_DEFENSE_MIDFIELD_PASSIVE = 21,
    AIPLAY_DEFENSE_DEFENDER_AGGRESSIVE = 22,
    AIPLAY_DEFENSE_DEFENDER_MODERATE = 23,
    AIPLAY_DEFENSE_DEFENDER_PASSIVE = 24,
    AIPLAY_LOOSE_STRIKER_AGGRESSIVE = 25,
    AIPLAY_LOOSE_STRIKER_MODERATE = 26,
    AIPLAY_LOOSE_STRIKER_PASSIVE = 27,
    AIPLAY_LOOSE_WINGER_AGGRESSIVE = 28,
    AIPLAY_LOOSE_WINGER_MODERATE = 29,
    AIPLAY_LOOSE_WINGER_PASSIVE = 30,
    AIPLAY_LOOSE_MIDFIELD_AGGRESSIVE = 31,
    AIPLAY_LOOSE_MIDFIELD_MODERATE = 32,
    AIPLAY_LOOSE_MIDFIELD_PASSIVE = 33,
    AIPLAY_LOOSE_DEFENDER_AGGRESSIVE = 34,
    AIPLAY_LOOSE_DEFENDER_MODERATE = 35,
    AIPLAY_LOOSE_DEFENDER_PASSIVE = 36,
    AIPLAY_GSTATE_PREKICKOFF = 37,
    AIPLAY_GSTATE_BALLOUTOFPLAY = 38,
    AIPLAY_GSTATE_POSTREDCARD = 39,
    AIPLAY_GSTATE_POSTGOAL = 40,
    AIPLAY_GSTATE_ENDHALF = 41,
    AIPLAY_GSTATE_ENDGAME = 42,
    NUM_AIPLAYS = 43,
};

class cDecisionEntity;

class AIPlay
{
public:
    AIPlay(cFielder* pFielder, eAIPlay eplayType, float fPlayDuration);
    ~AIPlay();
    void ClearPlay();
    bool IsPlayActive();
    void SetDuration(float fNewDuration);
    void SetPlayType(eAIPlay eNewAIPlay);
    void Update(float fDeltaT);
    void CalculateNewDesire();

    /* 0x0 */ eAIPlay meCurrentPlay;
    /* 0x4 */ cFielder* mpFielder;
    /* 0x8 */ float mfPlayDuration;
    /* 0xC */ cDecisionEntity* mpPlayDE;
};

#endif // _AIPLAY_H_
