#ifndef _WORLDAUDIO_H_
#define _WORLDAUDIO_H_

#include "types.h"
#include "Game/GameAudio.h"

class SoundPropAccessor;

namespace Audio
{

enum eWorldSFX
{
    WORLDSFX_NONE = 0,
    WORLDSFX_PLACEHOLDER = 1,
    WORLDSFX_FE_TOGGLE = 2,
    WORLDSFX_FE_TOGGLE_02 = 3,
    WORLDSFX_FE_TOGGLE_03 = 4,
    WORLDSFX_FE_TOGGLE_PULSE_01 = 5,
    WORLDSFX_FE_BUTTON_GEN_SELECT_ACCEPT = 6,
    WORLDSFX_FE_SCREEN_GEN_BEGIN = 7,
    WORLDSFX_FE_BUTTON_GEN_SELECT_BACK = 8,
    WORLDSFX_FE_SCREEN_GEN_END = 9,
    WORLDSFX_FE_FLASH = 10,
    WORLDSFX_FE_LETTER_FLY_IN = 11,
    WORLDSFX_FE_LETTER_HIT = 12,
    WORLDSFX_FE_LIGHT_TEXT_FLY_IN = 13,
    WORLDSFX_FE_LIGHT_TEXT_FLY_IN_LEFT = 14,
    WORLDSFX_FE_LIGHT_TEXT_FLY_IN_RIGHT = 15,
    WORLDSFX_FE_MENU_OVERLAY_DROP = 16,
    WORLDSFX_FE_LETTER_ROTATE_LOOP = 17,
    WORLDSFX_FE_DENY = 18,
    WORLDSFX_FE_USER_QUESTION = 19,
    WORLDSFX_FE_USER_POPUP = 20,
    WORLDSFX_FE_TOGGLE_STADIUM = 21,
    WORLDSFX_FE_ACCEPT_STADIUM = 22,
    WORLDSFX_FE_STADIUM_LETTER_HIT = 23,
    WORLDSFX_FE_STADIUM_LETTER_FLY_IN = 24,
    WORLDSFX_FE_STINGER_SFX_01 = 25,
    WORLDSFX_FE_ACCEPT_MARIO = 26,
    WORLDSFX_FE_ACCEPT_WARIO = 27,
    WORLDSFX_FE_ACCEPT_LUIGI = 28,
    WORLDSFX_FE_ACCEPT_WALUIGI = 29,
    WORLDSFX_FE_ACCEPT_PEACH = 30,
    WORLDSFX_FE_ACCEPT_DAISY = 31,
    WORLDSFX_FE_ACCEPT_DK = 32,
    WORLDSFX_FE_ACCEPT_YOSHI = 33,
    WORLDSFX_FE_ACCEPT_TOAD = 34,
    WORLDSFX_FE_ACCEPT_KOOPA = 35,
    WORLDSFX_FE_ACCEPT_BIRDO = 36,
    WORLDSFX_FE_ACCEPT_HAM = 37,
    WORLDSFX_FE_ACCEPT_MYSTERY = 38,
    WORLDSFX_FE_NLG_MARIO = 39,
    WORLDSFX_FE_NLG_WARIO = 40,
    WORLDSFX_FE_NLG_LUIGI = 41,
    WORLDSFX_FE_NLG_WALUIGI = 42,
    WORLDSFX_FE_NLG_PEACH = 43,
    WORLDSFX_FE_NLG_DAISY = 44,
    WORLDSFX_FE_NLG_DK = 45,
    WORLDSFX_FE_NLG_YOSHI = 46,
    WORLDSFX_FE_NLG_TOAD = 47,
    WORLDSFX_FE_NLG_KOOPA = 48,
    WORLDSFX_FE_NLG_BIRDO = 49,
    WORLDSFX_FE_NLG_HAM = 50,
    WORLDSFX_FE_NLG_CRITTER = 51,
    WORLDSFX_FE_NLG_MYSTERY = 52,
    WORLDSFX_FE_NINTENDO_MARIO = 53,
    WORLDSFX_FE_NINTENDO_WARIO = 54,
    WORLDSFX_FE_NINTENDO_LUIGI = 55,
    WORLDSFX_FE_NINTENDO_WALUIGI = 56,
    WORLDSFX_FE_NINTENDO_PEACH = 57,
    WORLDSFX_FE_NINTENDO_DAISY = 58,
    WORLDSFX_FE_NINTENDO_DK = 59,
    WORLDSFX_FE_NINTENDO_YOSHI = 60,
    WORLDSFX_FE_NINTENDO_TOAD = 61,
    WORLDSFX_FE_NINTENDO_KOOPA = 62,
    WORLDSFX_FE_NINTENDO_BIRDO = 63,
    WORLDSFX_FE_NINTENDO_HAM = 64,
    WORLDSFX_FE_NINTENDO_CRITTER = 65,
    WORLDSFX_FE_NINTENDO_MYSTERY = 66,
    WORLDSFX_FE_FOCUS_MARIO = 67,
    WORLDSFX_FE_FOCUS_WARIO = 68,
    WORLDSFX_FE_FOCUS_LUIGI = 69,
    WORLDSFX_FE_FOCUS_WALUIGI = 70,
    WORLDSFX_FE_FOCUS_PEACH = 71,
    WORLDSFX_FE_FOCUS_DAISY = 72,
    WORLDSFX_FE_FOCUS_DK = 73,
    WORLDSFX_FE_FOCUS_YOSHI = 74,
    WORLDSFX_FE_FOCUS_MYSTERY = 75,
    WORLDSFX_HUD_WHISTLE_PLAY_START = 76,
    WORLDSFX_HUD_WHISTLE_PLAY_STOP = 77,
    WORLDSFX_HUD_REPLAY_SWIPE = 78,
    WORLDSFX_HUD_BALL_HIT_CAMERA = 79,
    WORLDSFX_HUD_CLOCK_COUNT = 80,
    WORLDSFX_HUD_TOGGLE_UP = 81,
    WORLDSFX_HUD_TOGGLE_DOWN = 82,
    WORLDSFX_HUD_ACCEPT = 83,
    WORLDSFX_FILTER_START = 84,
    WORLDSFX_FILTER_END = 85,
    REPLAYSFX_CAMERA_ZOOM_IN = 86,
    REPLAYSFX_CAMERA_ZOOM_OUT = 87,
    REPLAYSFX_CAMERA_SPEED_UP = 88,
    REPLAYSFX_CAMERA_SLOW_DOWN = 89,
    NISSFX_STOS_GEN_HAMMER = 90,
    PWRUPSFX_SHELL_GEN_MOVE = 91,
    PWRUPSFX_SHELL_GEN_SHATTER = 92,
    PWRUPSFX_SHELL_GEN_ACQUIRE = 93,
    PWRUPSFX_SHELL_RED_ACQUIRE = 94,
    PWRUPSFX_SHELL_RED_ACTIVATE = 95,
    PWRUPSFX_SHELL_RED_MOVE = 96,
    PWRUPSFX_SHELL_RED_HIT = 97,
    PWRUPSFX_SHELL_RED_BOUNCE_WALL = 98,
    PWRUPSFX_SHELL_RED_BOUNCE_GROUND = 99,
    PWRUPSFX_SHELL_GREEN_ACQUIRE = 100,
    PWRUPSFX_SHELL_GREEN_ACTIVATE = 101,
    PWRUPSFX_SHELL_GREEN_MOVE = 102,
    PWRUPSFX_SHELL_GREEN_HIT = 103,
    PWRUPSFX_SHELL_GREEN_BOUNCE_WALL = 104,
    PWRUPSFX_SHELL_GREEN_BOUNCE_GROUND = 105,
    PWRUPSFX_SHELL_FREEZE_ACQUIRE = 106,
    PWRUPSFX_SHELL_FREEZE_ACTIVATE = 107,
    PWRUPSFX_SHELL_FREEZE_MOVE = 108,
    PWRUPSFX_SHELL_FREEZE_HIT = 109,
    PWRUPSFX_SHELL_FREEZE_BOUNCE_WALL = 110,
    PWRUPSFX_SHELL_FREEZE_BOUNCE_GROUND = 111,
    PWRUPSFX_SHELL_SPINY_ACQUIRE = 112,
    PWRUPSFX_SHELL_SPINY_ACTIVATE = 113,
    PWRUPSFX_SHELL_SPINY_MOVE = 114,
    PWRUPSFX_SHELL_SPINY_HIT = 115,
    PWRUPSFX_SHELL_SPINY_BOUNCE_WALL = 116,
    PWRUPSFX_SHELL_SPINY_BOUNCE_GROUND = 117,
    PWRUPSFX_MUSH_ACQUIRE = 118,
    PWRUPSFX_MUSH_ACTIVATE = 119,
    PWRUPSFX_MUSH_END = 120,
    PWRUPSFX_BANA_ACQUIRE = 121,
    PWRUPSFX_BANA_ACTIVATE = 122,
    PWRUPSFX_BANA_BOUNCE = 123,
    PWRUPSFX_BANA_HIT = 124,
    PWRUPSFX_STAR_ACQUIRE = 125,
    PWRUPSFX_STAR_ACTIVATE = 126,
    PWRUPSFX_STAR_HIT = 127,
    PWRUPSFX_STAR_END = 128,
    PWRUPSFX_BOMB_ACQUIRE = 129,
    PWRUPSFX_BOMB_ACTIVATE = 130,
    PWRUPSFX_BOMB_MOVE = 131,
    PWRUPSFX_BOMB_HIT = 132,
    PWRUPSFX_BOMB_END = 133,
    PWRUPSFX_CHOMP_ACQUIRE = 134,
    PWRUPSFX_CHOMP_ACTIVATE = 135,
    PWRUPSFX_CHOMP_MOVE = 136,
    PWRUPSFX_CHOMP_HIT = 137,
    PWRUPSFX_CHOMP_BOUNCE = 138,
    PWRUPSFX_CHOMP_BARK = 139,
    CROWDSFX_GOAL_HOME = 140,
    CROWDSFX_GOAL_AWAY = 141,
    CROWDSFX_LOOP_POS = 142,
    CROWDSFX_LOOP_NEU = 143,
    CROWDSFX_LOOP_NEG = 144,
    CROWDSFX_LOOP_BOO = 145,
    CROWDSFX_LOOP_ANT = 146,
    CROWDSFX_LOOP_WHISTLE = 147,
    CROWDSFX_EVENT_YEAH_BIG = 148,
    CROWDSFX_EVENT_YEAH_SMALL1 = 149,
    CROWDSFX_EVENT_YEAH_SMALL2 = 150,
    CROWDSFX_EVENT_YEAH_SMALL3 = 151,
    CROWDSFX_EVENT_ANT_BIG = 152,
    CROWDSFX_EVENT_ANT_SMALL = 153,
    CROWDSFX_EVENT_OH_BIG1 = 154,
    CROWDSFX_EVENT_OH_BIG2 = 155,
    CROWDSFX_EVENT_OH_BIG3 = 156,
    CROWDSFX_EVENT_OH_SMALL1 = 157,
    CROWDSFX_EVENT_OH_SMALL2 = 158,
    CROWDSFX_EVENT_OH_SMALL3 = 159,
    CROWDSFX_EVENT_OH_SMALL4 = 160,
    CROWDSFX_EVENT_CLAP_BIG = 161,
    CROWDSFX_EVENT_CLAP_SMALL = 162,
    CROWDSFX_EVENT_JEER_BIG = 163,
    CROWDSFX_EVENT_JEER_SMALL = 164,
    CROWDSFX_EVENT_BOO_SMALL1 = 165,
    CROWDSFX_EVENT_BOO_SMALL2 = 166,
    CROWDSFX_EVENT_BOO_SMALL3 = 167,
    CROWDSFX_EVENT_BOO_BIG1 = 168,
    CROWDSFX_EVENT_BOO_BIG2 = 169,
    CROWDSFX_EVENT_BOO_BIG3 = 170,
    BALLSFX_HEADER = 171,
    BALLSFX_CHEST = 172,
    BALLSFX_KICK = 173,
    BALLSFX_KICK_ONETIMER = 174,
    BALLSFX_KICK_S2S_CAPT = 175,
    BALLSFX_PASS = 176,
    BALLSFX_PASS_RECEIVE = 177,
    BALLSFX_PASS_VOLLEY = 178,
    BALLSFX_PASS_VOLLEY_FLY = 179,
    BALLSFX_PASS_PERFECT_FLY = 180,
    BALLSFX_KICK_HARD = 181,
    BALLSFX_KICK_S2S_REG = 182,
    BALLSFX_KICK_S2S_FLAME = 183,
    BALLSFX_THROW = 184,
    BALLSFX_SLAP = 185,
    BALLSFX_CATCH = 186,
    BALLSFX_CATCH_MOUTH = 187,
    BALLSFX_DRIBBLE_WALK = 188,
    BALLSFX_DRIBBLE_RUN = 189,
    STADSFX_BALL_HITS_NET_HARD = 190,
    STADSFX_BALL_HITS_NET_SOFT = 191,
    STADSFX_BALL_HITS_POST = 192,
    STADSFX_BALL_HITS_FORCE_FIELD = 193,
    STADSFX_BALL_BOUNCE = 194,
    STADSFX_BALL_ROLL = 195,
    STADSFX_GEN_HORN_GOAL = 196,
    STADSFX_GEN_HALF_END_WARNING = 197,
    STADSFX_GEN_FIREWORKS_FLOOR = 198,
    STADSFX_GEN_FIREWORKS_CEILING = 199,
    STADSFX_GEN_CAMERA_SHAKE = 200,
    STADSFX_GEN_SIDELINE_EXPLODE = 201,
    STADSFX_GEN_NIS_FORCE_FIELD = 202,
    NUM_WORLDSFX = 203,
};

class cWorldSFX : public cGameSFX
{
public:
    enum CrowdReactionType
    {
        CROWD_REACTION_OH_BIG = 0,
        CROWD_REACTION_OH_SMALL = 1,
        CROWD_REACTION_YEAH_SMALL = 2,
        CROWD_REACTION_BOO_SMALL = 3,
        CROWD_REACTION_BOO_BIG = 4,
    };

    cWorldSFX()
        : cGameSFX()
    {
        // cGameSFX::Init();
        meClassType = WORLD;
    };
    virtual ~cWorldSFX();
    virtual void Init();
    virtual void SetSFX(SoundPropAccessor* pSoundPropAccessor);
    virtual uintptr_t Play(Audio::SoundAttributes& attributes);

    unsigned long Play(Audio::eWorldSFX sfx, float volume, float delayTime, bool keepTrack, float panning);
    unsigned long PlayRandomReaction(Audio::cWorldSFX::CrowdReactionType dType, float volume, float delayTime, int groupPriority, float fDefaultVolAdjustment);

    void Stop(Audio::eWorldSFX sfx, cGameSFX::StopFlag flag);
};

extern Audio::cWorldSFX gWorldSFX;
extern Audio::cWorldSFX gPowerupSFX;
extern Audio::cWorldSFX gStadGenSFX;
extern Audio::cWorldSFX gCrowdSFX;
extern bool g_bWorldSFXInitialized;
extern bool g_bAudioInitialized;
extern SoundStrToIDNode gWorldSFXInfo[];
extern int gWorldSoundTypeEnumMap[];
extern const char* gWorldSoundTable[];

} // namespace Audio

#endif // _WORLDAUDIO_H_
